apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: kumarnalini/flask-app
        ports:
        - containerPort: 5000
        env:
          - name: AUTH_USER
            valueFrom:
              secretKeyRef:
                name: flask-app-secrets
                key: AUTH_USER
          - name: AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: flask-app-secrets
                key: AUTH_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secrets
type: Opaque
data:
  AUTH_USER: dXNlcg==
  AUTH_PASSWORD: dXNlcg==
